# Generated by Django 4.0.5 on 2022-06-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='cfc_app.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pick', models.IntegerField(default=1)),
                ('live', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FbsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_abbrev', models.CharField(blank=True, max_length=10, null=True)),
                ('nickname', models.CharField(max_length=50)),
                ('conference_abbrev', models.CharField(max_length=12)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('conference_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='cfc_app.conference')),
                ('division_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='cfc_app.division')),
                ('owned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.IntegerField(blank=True, null=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.fbsteam')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('player', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
