# Generated by Django 4.0.5 on 2022-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbsTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=50)),
                ('conference_abbrev', models.CharField(max_length=10)),
                ('ranking', models.IntegerField(null=True)),
            ],
        ),
    ]
