# Generated by Django 4.0.5 on 2022-06-02 22:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FbsTeams',
            new_name='FbsTeam',
        ),
    ]
