# Generated by Django 4.0.5 on 2022-06-21 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0002_alter_draft_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
