# Generated by Django 4.0.5 on 2022-08-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0003_alter_draft_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbsteam',
            old_name='ranking',
            new_name='ap_ranking',
        ),
    ]
