# Generated by Django 4.0.5 on 2022-06-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0003_alter_pick_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbsteam',
            options={'ordering': ['id']},
        ),
    ]
