# Generated by Django 4.0.5 on 2022-06-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0003_rename_fbsteams_fbsteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbsteam',
            old_name='conference',
            new_name='conference_name',
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfc_app.fbsteam')),
            ],
        ),
    ]
