# Generated by Django 4.0.5 on 2022-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0004_rename_conference_fbsteam_conference_name_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
