# Generated by Django 4.0.5 on 2022-06-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0004_alter_fbsteam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsteam',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
