# Generated by Django 4.0.5 on 2022-08-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0004_rename_ranking_fbsteam_ap_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbsteam',
            old_name='ap_ranking',
            new_name='ap_preseason_ranking',
        ),
    ]
