# Generated by Django 4.0.5 on 2022-06-02 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0005_conference_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fbsteam',
            name='conference_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfc_app.conference'),
        ),
    ]
