# Generated by Django 4.0.5 on 2022-08-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0005_rename_ap_ranking_fbsteam_ap_preseason_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsteam',
            name='cbs_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbsteam',
            name='fpi_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
