# Generated by Django 4.0.5 on 2022-06-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0006_alter_conference_name_alter_fbsteam_conference_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbsteam',
            old_name='conference_name',
            new_name='division_name',
        ),
        migrations.AlterField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfc_app.conference')),
            ],
        ),
    ]
