# Generated by Django 4.0.5 on 2022-06-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0007_rename_conference_name_fbsteam_division_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsteam',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.conference'),
        ),
        migrations.AlterField(
            model_name='fbsteam',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
