# Generated by Django 4.0.5 on 2022-06-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0008_alter_fbsteam_division_name_alter_fbsteam_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsteam',
            name='conference_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.conference'),
        ),
        migrations.AlterField(
            model_name='fbsteam',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.division'),
        ),
    ]
