# Generated by Django 4.0.5 on 2022-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0009_fbsteam_conference_name_alter_fbsteam_division_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsteam',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
