# Generated by Django 4.0.5 on 2022-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0010_alter_fbsteam_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsteam',
            name='school_abbrev',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
