# Generated by Django 4.0.5 on 2022-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0011_fbsteam_school_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsteam',
            name='conference_abbrev',
            field=models.CharField(max_length=12),
        ),
    ]
