# Generated by Django 4.0.5 on 2022-06-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0012_alter_fbsteam_conference_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='cfc_app.conference'),
        ),
    ]
