# Generated by Django 4.0.5 on 2022-06-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0013_alter_division_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsteam',
            name='conference_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='cfc_app.conference'),
        ),
        migrations.AlterField(
            model_name='fbsteam',
            name='division_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='cfc_app.division'),
        ),
    ]
