# Generated by Django 4.0.5 on 2022-06-08 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0015_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='player',
        ),
        migrations.AddField(
            model_name='league',
            name='player',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
