# Generated by Django 4.0.5 on 2022-06-08 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0017_alter_league_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cfc_app.fbsteam')),
            ],
        ),
    ]
