# Generated by Django 4.0.5 on 2022-06-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0018_draft_pick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='number',
            new_name='pick_number',
        ),
    ]
