# Generated by Django 4.0.5 on 2022-06-08 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0019_rename_number_pick_pick_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='player',
        ),
        migrations.AddField(
            model_name='draft',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
