# Generated by Django 4.0.5 on 2022-06-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfc_app', '0021_alter_pick_draft_alter_pick_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picks', to=settings.AUTH_USER_MODEL),
        ),
    ]
