# Generated by Django 4.0.5 on 2022-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0022_alter_pick_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='current_pick',
            field=models.IntegerField(default=1),
        ),
    ]
