# Generated by Django 4.0.4 on 2022-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0023_draft_current_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='pick_number',
            field=models.IntegerField(null=True),
        ),
    ]
