# Generated by Django 4.0.4 on 2022-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0024_alter_pick_pick_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='pick_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
