# Generated by Django 4.0.5 on 2022-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0025_alter_pick_pick_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
