# Generated by Django 4.0.5 on 2022-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='draft_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
